"""Auto-sync satellite: re-check public status & re-sort videos.
Only updates src/videos.ts — index.html is regenerated by generate_videos_ts.py."""
import json, re, urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TS_PATH = REPO / "src" / "videos.ts"
CACHE_PATH = REPO / "data" / "public_cache.json"
CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)

cache = {}
if CACHE_PATH.exists():
    cache = json.loads(CACHE_PATH.read_text("utf-8"))

def parse_videos_ts(text):
    entries = []
    for line in text.splitlines():
        m = re.search(r'\{\s*id:\s*"([^"]+)"', line)
        if not m:
            continue
        vid = m.group(1)
        title = re.search(r'title:\s*"([^"]+)"', line)
        topic = re.search(r'topic:\s*"([^"]+)"', line)
        blurb = re.search(r'blurb:\s*"([^"]+)"', line)
        file = re.search(r'file:\s*"([^"]+)"', line)
        thumb = re.search(r'thumb:\s*(true|false)', line)
        date = re.search(r'date:\s*"([^"]+)"', line)
        pub = re.search(r'public:\s*(true|false)', line)
        entries.append({
            "id": vid,
            "title": title.group(1) if title else "",
            "topic": topic.group(1) if topic else "",
            "blurb": blurb.group(1) if blurb else "",
            "file": file.group(1) if file else "",
            "thumb": thumb.group(1) == "true" if thumb else False,
            "date": date.group(1) if date else "",
            "public": pub.group(1) == "true" if pub else False,
        })
    return entries

def is_public(vid, force=False):
    if not force and vid in cache:
        return cache[vid]
    url = f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={vid}&format=json"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    try:
        urllib.request.urlopen(req, timeout=10)
        cache[vid] = True
        return True
    except Exception:
        cache[vid] = False
        return False

def has_thumb(vid):
    url = f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"
    req = urllib.request.Request(url)
    req.add_header("User-Agent", "Mozilla/5.0")
    try:
        r = urllib.request.urlopen(req, timeout=5)
        return len(r.read()) > 1000
    except Exception:
        return False

def rewrite_videos_ts(entries):
    lines = [
        "// Auto-generated -- do not edit manually",
        "// Run: python scripts/sync.py",
        "",
        "export interface Video {",
        '  id: string;',
        '  title: string;',
        '  topic: string;',
        '  blurb: string;',
        '  file: string;',
        '  thumb: boolean;',
        '  date: string;',
        '  public: boolean;',
        "}",
        "",
        "export const VIDEOS: Video[] = [",
    ]
    for e in entries:
        title = e["title"].replace("\\", "\\\\").replace('"', "'")
        blurb = e["blurb"].replace("\\", "\\\\").replace('"', "'")
        lines.append(f'  {{ id: "{e["id"]}", title: "{title}", topic: "{e["topic"]}", blurb: "{blurb}", file: "{e["file"]}", thumb: {"true" if e["thumb"] else "false"}, date: "{e["date"]}", public: {"true" if e["public"] else "false"} }},')
    lines.append("];")
    lines.append("")
    TS_PATH.write_text("\n".join(lines), encoding="utf-8")

text = TS_PATH.read_text("utf-8")
entries = parse_videos_ts(text)

changed = False
for e in entries:
    current = is_public(e["id"], force=not e["public"])
    if current != e["public"]:
        print(f"[sync] {e['id']}: public={current} (was {e['public']})")
        e["public"] = current
        e["thumb"] = has_thumb(e["id"])
        changed = True

if not changed:
    print("[sync] No changes")
    CACHE_PATH.write_text(json.dumps(cache), encoding="utf-8")
    raise SystemExit(0)

entries.sort(key=lambda e: e["date"], reverse=True)
entries.sort(key=lambda e: 0 if e["public"] else 1)

rewrite_videos_ts(entries)
CACHE_PATH.write_text(json.dumps(cache), encoding="utf-8")
print(f"[sync] Updated: {sum(1 for e in entries if e['public'])} public / {sum(1 for e in entries if not e['public'])} scheduled")
